config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # We could restrict the use of Blazer to admin users only by uncommenting the next lines
  # authenticate :user, ->(user) { user.admin? } do
  mount Blazer::Engine, at: "blazer"
  # endmount Blazer::Engine, at: "blazer"

  resources :projects do
    resources :tasks, only: [:index, :new, :create, :edit, :update]
    resources :files, only: :destroy
  end

  resources :tasks, only: [:show, :destroy] do
    resources :assignments, only: [:create, :destroy]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get "calendar", to: "pages#calendar"

  get "landing", to: "pages#landing"
  
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :assignments, dependent: :destroy
  has_many :users, through: :assignments
  has_rich_text :notes

  validates :name, :description, :due_date, :estimated_effort, presence: true
  STATUS = ["Open", "In progress", "Completed", "Cancelled"]
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :show, :edit, :update, :destroy ]
  before_action :set_project, only: [:new, :create, :update]

  def index
    @tasks = Task.where(project_id: @project)
  end

  def show
    @users_available = User.where.not(id: @task.users)
    @project = @task.project
    if params[:query].present?
      @users_available = User.search_by_name(params[:query]).where.not(id: @task.users)
    else
      @users_available = User.where.not(id: @task.users)
    end
  end

  def new
    @task = Task.new
    @task.project = @project
    authorize @task
  end

  def create
    @task = Task.new(task_params)
    authorize @task
    @task.project = @project
    if @task.save
      redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @project = @task.project
  end

  def update
    if @task.update(task_params)
      redirect_to(request.referrer || root_path)

    else
      render :edit
    end
  end

  def destroy
    @project = @task.project
    @task.destroy
    redirect_to project_path(@project)
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :estimated_effort, :due_date, :notes, :status)
  end

  def set_task
    @task = Task.find(params[:id])
    authorize @task
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

end

app/views/tasks/_active_text_form.html.erb
<%= simple_form_for [@project, @task] do |f| %>
   <div class="form-input">
    <%= f.label :notes, class: "notes-label" %>

      <%= f.rich_text_area :notes, placeholder: 'Write your notes', class: "scroll_field" %>

    <%= f.submit "Update notes" %>
  </div>
<% end %>

app/views/tasks/_task_form.html.erb
  <%= simple_form_for [project, task] do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :due_date %>
            <%= f.input :estimated_effort %>
            <%= f.input :status, collection: Task::STATUS %>
            <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  <br>

app/views/tasks/edit.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-8">
      <h1>Edit this task</h1>
    </div>
    <div class="col-4" style= "align-self: center;">
      <%= link_to task_path(@task), class: 'btn btn-ghost-pshow' do %>
          <i class="fa fa-history"></i> Back to project
        <% end %>
    </div>
  </div>
    <%= render 'task_form', task: @task %>
</div>

app/views/tasks/new.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-8">
      <h1>Add a new task</h1>
    </div>
    <div class="col-4" style= "align-self: center;">
      <%= link_to project_path(@project), class: 'btn btn-ghost-pshow' do %>
          <i class="fa fa-history"></i> Back to project
        <% end %>
    </div>
  </div>
  <%= render 'task_form', project: @project, task: @task %>
</div>

app/views/tasks/show.html.erb
  <hr>
<div class="p-5">
  <div class="container">
    <div class="page-header">
      <div class="row title-add-new">
        <h1 class="col-auto"> <%= @project.name.truncate(15) %> > <%= @task.name%> </h1>
        <div class="col-auto icon-col">
          <i class="fas fa-pencil-alt" data-bs-toggle="modal" data-bs-target="#form_task_update"></i>
        </div>
      </div>
    <div class="row row upper-margin justify-content-between align-items-center mb-3">
      <div class="col-6">
        <div class="cards-container">
        <p class="box-title">
          DESCRIPTION
          </p>
        <p class="indications page-subheader"><%= @task.description %> </p>
        </div>
      </div>
      <div class="col-3 d-flex justify-content-center">
        <%= link_to task_path(@task), class: 'btn btn-ghost-pshow', method: 'delete', data: { confirm: "Are you sure you want to delete?" }  do %>
            <i class="fas fa-trash-alt"></i> Delete this task
          <% end %>
      </div>
      <div class="col-3 d-flex justify-content-center">
        <%= link_to project_path(@task.project), class: 'btn btn-ghost-pshow' do %>
            <i class="fa fa-history"></i> Back to project
          <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-3">
        <p class="button-39">Due date: <%= @task.due_date %></p>
      </div>
      <div class="col-3">
      <p class="button-39">Estimated effort: <%= @task.estimated_effort %>h</p>
      </div>
      <div class="col-3">
        <p class="button-39">Status: <%= @task.status %></p>

      </div>
      <div class="col-3">
        <p class="button-39">Completion date: <%= @task.completion_date %></p>
      </div>
    </div>
    <br>

    <div class="cards-container mt-3">
      <h4>Your Project Team</h4>
      <div class="row">
        <div class="col-6">
          <div class="insider-container">
            <h5 id='top-of-list'>Workers assigned to this task </h5>
            <p class="indications"><i >click to unassign</i></p>
            <div class="d-flex">
              <% @task.users.order('name asc').each do |user| %>
                    <% if user.avatar.attached? %>
                      <%= link_to task_assignment_path(@task, user_id: user.id), method: :delete,
                        data: { bs: { toggle: "tooltip", placement: "top", custom: { class: "custom-tooltip" } } },
                        title: user.name, type: "button" do %>
                          <%= image_tag user.avatar, class: "avatar m-0" %>
                      <% end %>
                    <% end %>
            <% end %>
            </div>
          </div>
        </div>
        <div class="col-6">
          <div class="insider-container">
            <h5 class="ui header">Workers not assigned to this task</h5>
            <div class="search-bar">
              <div class="col-auto icon-col">
                <i class="fas fa-search element-icon" aria-hidden="true"></i>
              </div>
              <div class="col-11">
                <%= form_tag task_path(@task), method: :get do %>
                  <%= text_field_tag :query,
                    params[:query],
                    class: "form-control-project search-user",
                    placeholder: "Find" %>
                <% end %>
              </div>
            </div>
            <span>
            <div class="ui inline dropdown">
              <ul>
                <% @users_available.order('name asc').each do |user| %>
                  <% if user.avatar.attached? %>
                    <%= link_to task_assignments_path(@task, user_id: user.id), method: :post,
                      data: { bs: { toggle: "tooltip", placement: "top", custom: { class: "custom-tooltip" } } },
                      title: user.name, type: "button" do %>
                        <%= image_tag user.avatar, class: "avatar m-0" %>
                    <% end %>
                  <% end %>
                <% end %>
              </ul>
            </div>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="cards-container mt-3">
      <%= render 'active_text_form', task: @task %>
    </div>
  </div>
</div>
</div>

<div class="modal fade" id="form_task_update" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style="padding:50px">
      <%= render "tasks/task_form", project: @project, task: @task %>
    </div>
  </div>
</div>