config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # We could restrict the use of Blazer to admin users only by uncommenting the next lines
  # authenticate :user, ->(user) { user.admin? } do
  mount Blazer::Engine, at: "blazer"
  # endmount Blazer::Engine, at: "blazer"

  resources :projects do
    resources :tasks, only: [:index, :new, :create, :edit, :update]
    resources :files, only: :destroy
  end

  resources :tasks, only: [:show, :destroy] do
    resources :assignments, only: [:create, :destroy]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get "calendar", to: "pages#calendar"

  get "landing", to: "pages#landing"
  
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-footer mt-3 px-3 border-top">

  <!-- Copyright -->
  <div class="p-4 bg-footer d-flex justify-content-between">
    <div class="copyright mt-3 px-3">
    <h3>© Copyrights: <strong>Mission:Possible</strong> 2022</h3>
    </div>
    <div class="logos">
        <a
          class="btn btn-primary btn-round btn-floating m-1 rounded-circle border-0"
          href="#!"
          role="button"
          ><i class="fab fa-twitter"></i
        ></a>
        <a
          class="btn btn-primary btn-round btn-floating m-1 rounded-circle border-0"
          href="#!"
          role="button"
          ><i class="fab fa-instagram"></i
        ></a>
        <a
          class="btn btn-primary btn-round btn-floating m-1 rounded-circle border-0"
          href="#!"
          role="button"
          ><i class="fab fa-github"></i
        ></a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-mp mb-3">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand mx-5 py-2" do %>
              <h4>Mission<strong>:Possible</strong></h4>
      <% end %>
      <div class="navbar-collapse">
        <ul class="navbar-nav me-auto">

          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "My Projects", projects_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "My calendar", calendar_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Dashboard", blazer_path, class: "nav-link" %>
            </li>
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "default-avatar-icon.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          <% else %>
            <li class="nav-item active">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Sign up", new_registration_path(resource_name), class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>