config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # We could restrict the use of Blazer to admin users only by uncommenting the next lines
  # authenticate :user, ->(user) { user.admin? } do
  mount Blazer::Engine, at: "blazer"
  # endmount Blazer::Engine, at: "blazer"

  resources :projects do
    resources :tasks, only: [:index, :new, :create, :edit, :update]
    resources :files, only: :destroy
  end

  resources :tasks, only: [:show, :destroy] do
    resources :assignments, only: [:create, :destroy]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get "calendar", to: "pages#calendar"

  get "landing", to: "pages#landing"
  
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :assignments, through: :tasks
  has_many :users, -> { distinct }, through: :assignments
  has_one :chatroom, dependent: :destroy
  has_many_attached :files, dependent: :destroy

  validates :name, :description, :due_date, presence: true
  validates :name, uniqueness: true

  after_save :create_chatroom

  STATUS = ["Open", "In progress", "Completed", "Cancelled"]

  private

  def create_chatroom
    Chatroom.create! project_id: self.id
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [ :show, :edit, :tasks_completed, :update, :destroy ]

  def new
    # @project = Project.new
    # authorize @project
  end

  def create
    @project = Project.new(project_params)
    authorize @project
    @project.user = current_user
    if @project.save
      redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    # instance variables for project modals (new and edit)
    @project = Project.new
    @project_update = nil

    # get projects for current user both as PM and contributor
    @projects_pm = policy_scope(Project).where(user_id: current_user).order(:name)
    @projects_worker = current_user.projects_as_contributor
    @today = "2022-06-18"

    # if a search parameter was passed for project name
    return unless params[:query].present?

    @projects_pm = Project.where(
      ["name ILIKE :name and user_id = :current_user", {
        name: "%#{params[:query]}%",
        current_user: current_user
      }]
    ).order(:name)

    @projects_worker.select! do |project|
      project.name.downcase.include?(params[:query].downcase)
    end
  end

  def show
    # instance variables for task modals (new and edit)
    @task = Task.new
    @task_update = nil

    #definir @tasks com base no filtro
    if params[:query].present?
      @tasks = Task.where(
        ["name ILIKE :name and project_id = :project_id",
          {name: "%#{params[:query]}%",
          project_id: @project.id
          }
        ]
      )
    else
      @tasks = @project.tasks
    end

    @tasks_status = @project.tasks
    @total_tasks = @tasks_status.count
    @total_completed = @tasks_status.select do |task_status|
      task_status.status == "Completed"
    end
    @tasks_count = @total_completed.count
    @progress = @tasks_count / @total_tasks.to_f
    @progress_percent = (@progress * 100)
  end

  def edit
  end

  def update
    if ok_to_complete_project?
      if @project.update(project_params)
        redirect_to project_path(@project)
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash[:alert] = "This project has open tasks."
      redirect_to project_path(@project)
      # render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
    authorize @project
  end

  def project_params
    params.require(:project).permit(:name, :description, :status, :price, :due_date, files: [])
  end

  def ok_to_complete_project?
    if params[:project][:status] == "Completed" &&
       params[:project][:status] != @project.status &&
       @project.tasks.where.not(status: "Completed").present?
      return false
    else
      return true
    end
  end
end

app/views/projects/_calendar.html.erb
<tbody>
  <% date_range.each_slice(7) do |dates| %>
    <tr>
      <% dates.each do |date| %>
        <%= content_tag :td, class: calendar.td_classes_for(date) do %>
          <% passed_block.call date.day, sorted_events.fetch(date, []) %>
        <% end %>
      <% end %>
    </tr>
  <% end %>
</tbody>

<%= month_calendar(attribute: :due_date, events: @projects) do |date, projects| %>
    <%= date %>
    <% projects.each do |project| %>
    <div class="project">
      <p><%= project.name %></p>
    </div>
    <% end %>
    <% end %>

app/views/projects/_form.html.erb
    <%= simple_form_for project do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :due_date %>
        <%= f.input :status, collection: Project::STATUS %>
        <%= f.file_field :files, multiple: true %>
        <div class="mt-3">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
    <% end %>
    <br>

app/views/projects/edit.html.erb
  <div class="row">
  <div class="col-8">
    <h1>Edit this project</h1>
  </div>
  <div class="col-4" style= "align-self: center;">
    <%= link_to project_path(@project), class: 'btn btn-ghost-pshow' do %>
        <i class="fa fa-history"></i> Back to project
      <% end %>
  </div>
  </div>
    <%= simple_form_for @project do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :due_date %>
        <%= f.input :status, collection: Project::STATUS %>
        <%= f.file_field :files, multiple: true %>
        <div class="side">
          <div class="form-actions mt-3">
            <%= f.button_button t(".Submit"), class: "btn-filled-general" %>
          </div>
        </div>
    <% end %>

app/views/projects/index.html.erb
<hr>
<div class="container">
  <div class="container">
    <div class="page-header">
      <div class="row title-add-new">
        <h1 class="col-auto">Your Projects</h1>
        <div class="col-auto icon-col">

          <i class="fas fa-plus-circle" data-bs-toggle="modal" data-bs-target="#form"></i>

        </div>
      </div>
      <h2 class="indications page-subheader">Hi <%= current_user.name.split(" ").first%> ! Let's see what's going on in your team 🚀 </h2>
    </div>


    <div class="search-bar">
      <div class="col-auto icon-col">
        <i class="fas fa-search element-icon" aria-hidden="true"></i>
      </div>
      <div class="col-11">
        <%= form_tag projects_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control-project",
            placeholder:  'Find a project'
          %>
        <% end %>
      </div>
    </div>

    <div class="row cards-container">
      <div class="col-6">
        <h3>Projects I am managing</h3>
        <ul class="list-group mb-3">
          <% @projects_pm.each do |project| %>
            <li>
              <div class="project-card">
                  <div class="project-card-infos">
                    <div>
                      <%= link_to project_path(project), class: 'project-info'  do %>
                        <h2><%= project.name.truncate(20) %> (<%= project.status %>)</h2>
                        <p><%= project.tasks.where.not(status: "Completed").count %> tasks in progress!</p>
                      <% end %>
                    </div>
                    <div class="project-actions project-card-actions ">
                      <% @project_update = project %>
                      <i class="fas fa-pencil-alt p-icon pt-1" data-bs-toggle="modal" data-bs-target="#form_update_<%=project.id%>"></i>
                      <%= link_to project_path(project), class: 'p-icon', method: 'delete', data: { confirm: "Are you sure you want to delete?" }  do %>
                        <i class="far fa-trash-alt"></i>
                      <% end %>
                    </div>
                  </div>
                  <div class="modal fade" id="form_update_<%=project.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content" style="padding:50px">
                        <div class="modal-body">
                          <%= render "form", project: @project_update %>
                        </div>
                      </div>
                    </div>
                  </div>
                <div class="project-card-infos">
                <div class="d-flex">
                  <% project.users.each do |user| %>
                    <%= link_to "#", data: { bs: { toggle: "tooltip", placement: "top",
                                     custom: { class: "custom-tooltip" } } },
                                     title: user.name, type: "button" do %>
                      <%= image_tag user.avatar, class: "avatar m-0" %>
                    <% end %>
                  <% end %>
                </div>
                  <h2 class="project-card-pricing">Due in <%= (project.due_date - Date.today).to_i %> days</h2>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="col-6">
        <h3>Projects I am working on</h3>
        <ul class="list-group mb-3">

          <% @projects_worker.each do |project| %>
            <li>
              <div class="project-card">
                  <div class="project-card-infos">
                    <div>
                      <%= link_to project_path(project), class: 'project-info'  do %>
                        <h2><%= project.name.truncate(20) %> (<%= project.status %>)</h2>
                        <p><%= project.tasks.where.not(status: "Completed").count %> tasks in progress!</p>
                      <% end %>
                    </div>
                    <div class="project-actions project-card-actions d-none">
                      <i class="fas fa-pencil-alt" data-bs-toggle="modal" data-bs-target="#form_update"></i>

                      <%= link_to project_path(project), class: 'p-icon', method: 'delete', data: { confirm: "Are you sure you want to delete?" }  do %>
                        <i class="far fa-trash-alt"></i>
                      <% end %>
                    </div>

                  </div>
                <div class="project-card-infos">
                <div class="d-flex">
                  <% project.users.each do |user| %>
                    <%= link_to "#", data: { bs: { toggle: "tooltip", placement: "top",
                                     custom: { class: "custom-tooltip" } } },
                                     title: user.name, type: "button" do %>
                      <%= image_tag user.avatar, class: "avatar m-0" %>
                    <% end %>
                  <% end %>
                </div>
                  <h2 class="project-card-pricing">Due in <%= (project.due_date - Date.today).to_i %> days</h2>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="form" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style="padding:50px" data-controller="mask">
      <div class="modal-body">
        <%= render "form", project: @project %>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container py-5">

  <h1>TELL US ABOUT YOUR NEW PROJECT!</h1>

  <br>

  <%= render 'form', project: @project %>

app/views/projects/show.html.erb
<hr>
<div class="p-5">
<div class="container mt-3">
  <h1 class="page-header"><%= @project.name %></h1>

  <div class="row align-items-center justify-content-around extra-margin">
    <div class="col-3">
        <p class="button-39">Due date: <%= @project.due_date %></p>
    </div>

    <div class="col-3">
        <p class="button-39">Status: <%= @project.status %></p>
    </div>

    <div class="col-3  d-flex justify-content-center">
      <%= link_to project_path(@project), class: 'btn btn-ghost-pshow', method: 'delete', data: { confirm: "Are you sure you want to delete?" }  do %>
        <i class="fas fa-trash-alt"></i> Delete this project
      <% end %>
    </div>

    <div class="col-3  d-flex justify-content-center">
      <%= link_to projects_path, class: 'btn btn-ghost-pshow' do %>
        <i class="fa fa-history"></i> Back to projects
      <% end %>
    </div>
  </div>

  <div class="cards-container-pview">

    <div class="row">
      <% if @progress_percent.nan? %>
        <p><%=@project.status%></p>
      <% else %>
        <% if @progress_percent == 0 %>
          <div class="progress p-0 pg-bar-style">
            <div class="progress-bar bg-danger" role="progressbar" style="width: 100%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">0% completed ⚡️</div>
          </div>
          <% elsif @progress_percent == 100 %>
          <div class="progress p-0 pg-bar-style">
            <div class="progress-bar bg-success" role="progressbar" style="width: <%=@progress_percent.to_i%>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">100% completed! &#127881</div>
          </div>
        <% else %>
          <div class="progress p-0 pg-bar-style">
            <div class="progress-bar bg-info" role="progressbar" style="width: <%=@progress_percent.to_i%>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><%=@progress_percent.to_i%>% completed 🤓 </div>
          </div>
        <% end %>
      <%end%>
    </div><!--.row-->

    <div class= "row upper-margin justify-content-between extra-padding">
      <div class="col-5 ">
        <div class="row title-add-new extra-padding">
          <h3 class="col-auto">Project Details</h1>
          <div class="col-auto icon-col">
            <i class="fas fa-pen" data-bs-toggle="modal" data-bs-target="#form_project_edit"></i>
          </div>
        </div>

        <div class="cards-container">
          <p class="box-title">
          DESCRIPTION
          </p>
          <p>
            <%= @project.description %>
          </p>
        </div>

        <div class="cards-container">
          <p class="box-title">
          PROJECT VALUE
          </p>
          <p>
            <%= @project.price %>$
          </p>
        </div>

         <div class="cards-container"><p class="box-title">FILES</p>    <!--attached files-->
            <% if @project.files.attached? %>
              <% @project.files.each do |file| %>
                <% if file.image? %>
                    <%= image_tag(file, :width => "260px")%>
                    <%= link_to 'remove file', project_file_path(@project, file), method: 'delete'%>
                <% else %>
                  <div class="container">
                    <%= link_to file.filename, rails_blob_path(file, disposition: "attachement"), target: "_blank"%>
                    <%= link_to 'remove file', project_file_path(@project, file), method: 'delete'%>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <p> No files attached yet </p>
            <% end %>
          </div>
          <div>
            <%= link_to 'Chatroom', chatroom_path(@project.chatroom), class: "btn btn-filled", style: "width: 95%"%>
          </div>
      </div>

      <div class="col-6">
        <div class="row title-add-new">
          <h3 class="col-auto">Tasks</h1>
          <div class="col-auto icon-col">
            <i class="fas fa-plus-circle" data-bs-toggle="modal" data-bs-target="#form_task_new"></i>
          </div>
        </div>

        <div class="search-bar">
          <div class="col-auto icon-col">
            <i class="fas fa-search element-icon" aria-hidden="true"></i>
          </div>
          <div class="col-11">
            <%= form_tag project_path, method: :get, :class => 'input-group' do %>     <!--searchbar-->
            <%= text_field_tag :query,params[:query], class: "form-control-project" %>
            <% end %>
          </div>
        </div>
        <div class="cards-container extra-margin">
          <% if @project.tasks.count > 0 %>
            <ul class="list-group"> <!--task list-->
              <% @tasks.each do |task| %>
                <li>
                  <div class="project-card ">
                    <div class="project-card-infos">
                      <div>
                        <%= link_to task_path(task), class: 'project-info'  do %>
                          <h2><%= task.name %></h2>
                          <p>(<%= task.status %>)</p>
                        <% end %>
                      </div>
                      <div class="project-actions project-card-actions ">
                        <% @task_update = task %>
                        <i class="fas fa-pencil-alt" data-bs-toggle="modal" data-bs-target="#form_task_update_<%=task.id%>"></i>
                        <%= link_to task_path(task), class: 'p-icon', method: 'delete', data: { confirm: "Are you sure you want to delete?" }  do %>
                          <i class="far fa-trash-alt"></i>
                        <% end %>
                      </div>

                      <div class="modal fade" id="form_task_update_<%=task.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content" style="padding:50px">
                            <%= render "tasks/task_form", project: @project, task: @task_update %>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="project-card-infos">
                      <div class="d-flex">
                        <% task.users.each do |user| %>
                          <% if user.avatar.attached? %>
                            <%= link_to "#", data: { bs: { toggle: "tooltip", placement: "top", custom: { class: "custom-tooltip" } } },
                                title: user.name, type: "button" do %>
                                  <%= image_tag user.avatar, class: "avatar m-0" %>
                            <% end %>
                          <% end %>
                        <% end %>
                      </div>

                      <h2 class="project-card-pricing">Effort: <%= task.estimated_effort%> h</h2>

                    </div>
                  </div>
                </li>
              <% end %>
            </ul>
          <% else %>
            <p>No tasks created yet</p>
          <% end %>
        </div>
      </div>
    </div><!--.row-->
  </div><!--.container-->
</div>


<div class="modal fade" id="form_project_edit" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style="padding:50px" data-controller="mask">
      <%= render "form", project: @project %>
    </div>
  </div>
</div>


<div class="modal fade" id="form_task_new" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style="padding:50px" data-controller="mask">
      <%= render "tasks/task_form", project: @project, task: @task %>
    </div>
  </div>
</div>

</div>